// src/components/MetalSwitch.vue
<template>
  <div class="flex items-center space-x-1 bg-slate-800 rounded-lg p-1">
    <button
      @click="$emit('metal-change', 'gold')"
      :class="[
        'flex items-center space-x-2 px-4 py-2 rounded-md transition-all duration-200',
        currentMetal === 'gold'
          ? 'bg-yellow-500 text-white shadow-lg'
          : 'text-slate-400 hover:text-yellow-400 hover:bg-slate-700'
      ]"
    >
      <Coins class="w-4 h-4" />
      <span class="font-medium">黄金</span>
    </button>

    <button
      @click="$emit('metal-change', 'silver')"
      :class="[
        'flex items-center space-x-2 px-4 py-2 rounded-md transition-all duration-200',
        currentMetal === 'silver'
          ? 'bg-gray-400 text-white shadow-lg'
          : 'text-slate-400 hover:text-gray-300 hover:bg-slate-700'
      ]"
    >
      <Gem class="w-4 h-4" />
      <span class="font-medium">白银</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { Coins, Gem } from 'lucide-vue-next'
import type { MetalType } from '../types/gold'

defineProps<{
  currentMetal: MetalType
}>()

defineEmits<{
  'metal-change': [metal: MetalType]
}>()
</script>

// src/components/MetalSwitch.tsx
import React from 'react';
import { Coins, Gem } from 'lucide-react';
import { MetalType } from '../types/gold';

interface MetalSwitchProps {
  currentMetal: MetalType;
  onMetalChange: (metal: MetalType) => void;
}

const MetalSwitch: React.FC<MetalSwitchProps> = ({ currentMetal, onMetalChange }) => {
  const metals = [
    {
      type: 'gold' as MetalType,
      name: '黄金',
      symbol: 'Au99.99',
      icon: Coins,
      color: 'text-yellow-400',
      activeColor: 'bg-yellow-500',
      hoverColor: 'hover:bg-yellow-500/20'
    },
    {
      type: 'silver' as MetalType,
      name: '白银',
      symbol: 'Ag99.99',
      icon: Gem,
      color: 'text-gray-300',
      activeColor: 'bg-gray-400',
      hoverColor: 'hover:bg-gray-400/20'
    }
  ];

  return (
    <div className="flex items-center space-x-2 bg-slate-800 rounded-lg p-1">
      {metals.map((metal) => {
        const Icon = metal.icon;
        const isActive = currentMetal === metal.type;

        return (
          <button
            key={metal.type}
            onClick={() => onMetalChange(metal.type)}
            className={`flex items-center space-x-2 px-3 py-2 rounded-md text-sm font-medium transition-all duration-200 ${
              isActive
                ? `${metal.activeColor} text-white shadow-md`
                : `text-slate-400 ${metal.hoverColor} hover:text-white`
            }`}
          >
            <Icon className={`w-4 h-4 ${isActive ? 'text-white' : metal.color}`} />
            <span>{metal.name}</span>
            <span className="text-xs opacity-75">({metal.symbol})</span>
          </button>
        );
      })}
    </div>
  );
};

export default MetalSwitch;
